AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Very simple SNS topic template


Resources:
  SNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: '{{ environment.inputs.topic_name }}''
      Subscription:
          - Endpoint: '{{ environment.inputs.subscription }}'
          
  
# These output values are will be available to service templates, given the
# the 'environment' namespace, for example, environment.outputs.ClusterName.
Outputs:
