AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Very simple SNS topic template


Resources:
  SNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: '{{ service_instance.inputs.topic_name }}'

  EmailSubscription:  
    Type: 'AWS::SNS::Subscription'  
    Properties:  
      Protocol: 'email'  
      TopicArn: !Ref SNS  
      Endpoint: '{{ service_instance.inputs.subscription }}'
          
  
# These output values are will be available to service templates, given the
# the 'environment' namespace, for example, environment.outputs.ClusterName.
# Outputs:
