schema:
  format:
    openapi: "3.0.0"
  service_input_type: "SNSInput"
  #pipeline_input_type: "PipelineInputs"

  types:
    SNSInput:
      type: object
      description: "Input properties for a SNS service"
      properties:
        topic_name:
          type: string
          description: "SNS topic name
          default: "my-topic-from-proton"
        subscription:
          type: string
          description: "Email address for SNS subscription"
          default: "foo@bar.com"
