schema:
  format:
    openapi: "3.0.0"
  service_input_type: "SNSinput"

  types:
    SNSinput:
      type: object
      description: "Input properties for a SNS service"
      properties:
        topic_name:
          type: string
          description: "Topic name"
          default: "my-topic"
          minLength: 1
          maxLength: 200
        subscription:
          type: string
          description: "Email address"
          default: "foo@bar.com"
          minLength: 1
          maxLength: 200

