AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda based HTTP service template



Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: '{{ environment.inputs.bucket_name }}'



# These output values are will be available to service templates, given the
# the 'environment' namespace, for example, environment.outputs.ClusterName.
# Outputs:
